# Generated by Django 4.2.15 on 2024-09-04 15:16

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('api', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='recept',
            name='author',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='recept', to=settings.AUTH_USER_MODEL, verbose_name='Автор рецепта'),
        ),
        migrations.AddField(
            model_name='recept',
            name='ingredients',
            field=models.ManyToManyField(through='api.IngredientRecept', to='api.ingredient', verbose_name='Ингредиенты рецепта'),
        ),
        migrations.AddField(
            model_name='recept',
            name='tags',
            field=models.ManyToManyField(through='api.TagRecept', to='api.tag', verbose_name='Теги рецепта'),
        ),
        migrations.AddField(
            model_name='ingredientrecept',
            name='ingredient',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.ingredient', verbose_name='Ингридиент'),
        ),
        migrations.AddField(
            model_name='ingredientrecept',
            name='recept',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.recept', verbose_name='Рецепт'),
        ),
        migrations.AddField(
            model_name='favorite',
            name='recept',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='favorited', to='api.recept'),
        ),
        migrations.AddField(
            model_name='favorite',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='cart',
            name='recept',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cart', to='api.recept'),
        ),
        migrations.AddField(
            model_name='cart',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cart', to=settings.AUTH_USER_MODEL, verbose_name='Пользователь'),
        ),
    ]
