# Generated by Django 4.2.15 on 2024-09-08 15:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='cart',
            options={'verbose_name_plural': 'Корзина'},
        ),
        migrations.AlterModelOptions(
            name='favorite',
            options={'verbose_name_plural': 'Избранное'},
        ),
        migrations.AlterModelOptions(
            name='ingredientrecept',
            options={'verbose_name_plural': 'Ингредиент и Рецепт'},
        ),
        migrations.AlterModelOptions(
            name='recept',
            options={'ordering': ['-id'], 'verbose_name': 'рецепт', 'verbose_name_plural': 'Рецепты'},
        ),
        migrations.AlterModelOptions(
            name='tagrecept',
            options={'verbose_name_plural': 'Таг и Рецепт'},
        ),
    ]
