# Generated by Django 4.2.15 on 2024-09-04 16:48

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('api', '0002_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ShortUrl',
        ),
        migrations.AlterModelOptions(
            name='cart',
            options={'verbose_name': 'Корзина'},
        ),
        migrations.AlterModelOptions(
            name='favorite',
            options={'verbose_name': 'Избранное'},
        ),
        migrations.AlterField(
            model_name='cart',
            name='recept',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cart', to='api.recept', verbose_name='Рецепт'),
        ),
        migrations.AlterField(
            model_name='favorite',
            name='recept',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='favorited', to='api.recept', verbose_name='Рецепт'),
        ),
        migrations.AlterField(
            model_name='favorite',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Пользователь'),
        ),
        migrations.AlterField(
            model_name='recept',
            name='short_url',
            field=models.CharField(blank=True, max_length=32, verbose_name='Короткая ссылка'),
        ),
        migrations.AlterField(
            model_name='tagrecept',
            name='recept',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.recept', verbose_name='Рецепт'),
        ),
        migrations.AlterField(
            model_name='tagrecept',
            name='tag',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.tag', verbose_name='Тег'),
        ),
    ]
