# Generated by Django 4.2.15 on 2024-09-01 21:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_alter_tag_recept_tag'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tag_recept',
            name='tag',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.tag'),
        ),
    ]
