# Generated by Django 4.2.15 on 2024-08-31 12:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_alter_ingredient_recept_ingredient_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ingredient_recept',
            name='ingredient',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.ingredient'),
        ),
        migrations.AlterField(
            model_name='ingredient_recept',
            name='recept',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.recept'),
        ),
    ]
