# Generated by Django 4.2.15 on 2024-09-08 15:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('persons', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='follower',
            options={'ordering': ['-id'], 'verbose_name_plural': 'Подписка'},
        ),
        migrations.AlterModelOptions(
            name='person',
            options={'verbose_name_plural': 'Пользователи'},
        ),
    ]
